//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceRegUltra.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanceRegUltra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*Таблица событий*/
        ///create table &apos;events&apos;
        ///(
        ///&apos;Id_event&apos; INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        ///&apos;Title&apos; TEXT DEFAULT &apos;&apos;,
        ///&apos;Start_timestamp&apos; LONG DEFAULT -1,
        ///&apos;End_timestamp&apos; LONG DEFAULT -1,
        ///&apos;Json_scheme&apos; TEXT DEFAULT &apos;&apos;,
        ///&apos;Id_node_increment&apos; INTERER NOT NULL DEFAULT 1,
        ///&apos;Judge_count&apos; INTEGER DEFAULT 4
        ///);
        ///
        ////*Таблица узлов, связанных с определенным событием*/
        ///create table &apos;event_nodes&apos;
        ///(
        ///&apos;Id_event&apos; INTEGER NOT NULL,
        ///&apos;Id_node&apos; INTEGER NOT NULL,
        ///&apos;Id_member&apos; INTEGER NOT NULL,
        ///&apos;Id_league&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dance {
            get {
                return ResourceManager.GetString("dance", resourceCulture);
            }
        }
    }
}
